### ISSUE TITLE
Port Registry from ZapJS to Python

### ISSUE THREAD

**Issue by pynchmeister** [zapproject/zappy#11]
# Summary

Port Registry from ZapJS to Python

## Reference

https://github.com/zapproject/zap-monorepo/blob/master/packages/Registry/src/index.ts

## Definition of Done

All the functions are able to called and return the correct values.

**Comment by george-karakyklas** [comment]
I will be working on this starting next week, also @pynchmeister just making sure "C++" is a typo, right? You meant python?

**Comment by acemasterjb** [comment]
This should be done, refer to pull #40
