### ISSUE TITLE
Port Arbiter from ZapJS to Python

### ISSUE THREAD

**Issue by pynchmeister** [zapproject/zappy#5]
# Summary 

Port Arbiter from ZapJS to Python

## Reference 

https://github.com/zapproject/zap-monorepo/blob/master/packages/Arbiter/src/index.ts

## Definition of Done

All the functions are able to called and return the correct values.

**Comment by DanFTW** [comment]
Charles is working on this task.

**Comment by charlesira** [comment]
I just made a pull request adding in parts of Arbiter, relevant types that were unported in types.py, and added the class for test cases for arbiter.
