### ISSUE TITLE
 fetchCurrentBidForBidder

### ISSUE THREAD

**Issue by Kaleb47** [zapproject/zappy#58]
### Description

In order for a user to set a bid, that user needs to know wha the current bid for an NFT is, so they can Bid against that.

### Definition of Done

- [ ] Write a function that takes the media address and token ID
- [ ] Returns the current bid for the NFT
- [ ] Test with the ganache CLI.
- [ ] Integrate error Handling so the function can revert if neither parameters exist.

**Comment by taejoonn** [comment]
To clarify, `bidForTokenBidder()` is a getter for the current bid the caller has made a bid on for a specified token and not for getting the current/highest bid on a token.
