### ISSUE TITLE
Port Bondage from ZapJS to Python

### ISSUE THREAD

**Issue by pynchmeister** [zapproject/zappy#7]
# Summary

Port Bondage from ZapJS to Python

## Reference

https://github.com/zapproject/zap-monorepo/blob/master/packages/Bondage/src/index.ts

## Definition of Done

All the functions should be able to be called and return the proper values.

**Comment by DanFTW** [comment]
George is tasked with this issue

**Comment by acemasterjb** [comment]
Going to be picking up on this.

**Comment by acemasterjb** [comment]
Please refer to pull request #45 for review of this port.
